services:
  postgres:
    image: 'postgres:alpine'
    container_name: postgres_db
    environment:
      - POSTGRES_DB=db_image_processing_service
      - POSTGRES_USER=user_image_processing_service
      - POSTGRES_PASSWORD=secret
    ports:
      - '5400:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - backend-network
  kafka:
    image: bitnami/kafka:latest
    container_name: my-kafka
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - zookeeper
    networks:
      - backend-network
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: my-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOO_ENABLE_AUTH=no
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend-network
volumes:
  postgres_data:
  kafka_logs:
networks:
  backend-network:
    driver: bridge